webtalk_init -webtalk_dir C:/Users/iGreen/Desktop/DESIGN AUTOMATION/HW3/vivado/Q5/Q5.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 06 18:56:35 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "41e91d07-3e9b-407a-90d7-bac4d4c47c8c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "778269fd-5765-448d-bb56-cc3f0889f660" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) CPU 1037U @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1796 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_transmit -clientid 3302465778 -regid "" -xml C:/Users/iGreen/Desktop/DESIGN AUTOMATION/HW3/vivado/Q5/Q5.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/iGreen/Desktop/DESIGN AUTOMATION/HW3/vivado/Q5/Q5.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/iGreen/Desktop/DESIGN AUTOMATION/HW3/vivado/Q5/Q5.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
