# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_Projects/FPGA_Project/new_project/new_project.cache/wt [current_project]
set_property parent.project_path D:/Vivado_Projects/FPGA_Project/new_project/new_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib D:/Vivado_Projects/FPGA_Project/new_project/new_project.srcs/sources_1/new/sorter.vhd
synth_design -top SORTER -part xc7vx485tffg1157-1
write_checkpoint -noxdef SORTER.dcp
catch { report_utilization -file SORTER_utilization_synth.rpt -pb SORTER_utilization_synth.pb }
