# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Admin/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Admin/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/Admin/Desktop/project_1/project_1.srcs/sources_1/imports/Q6/ORG.vhd
  C:/Users/Admin/Desktop/project_1/project_1.srcs/sources_1/imports/Q6/ANDG.vhd
  C:/Users/Admin/Desktop/project_1/project_1.srcs/sources_1/imports/Q6/Test.vhd
}
synth_design -top Test -part xc7vx485tffg1157-1
write_checkpoint -noxdef Test.dcp
catch { report_utilization -file Test_utilization_synth.rpt -pb Test_utilization_synth.pb }
